<a href="https://colab.research.google.com/github/nikhild738ND/OpsPilot_Operations_Decision_Intelligence/blob/main/notebooks/01_source_data_profile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SF311 Source Data Profile

This notebook is my first look at the SF311 source data used for OpsPilot.

The goal here is not to clean or model the data yet. I want to understand the schema, check the fields needed for the main KPIs, and identify any obvious data-quality issues before building the warehouse.

Dataset: San Francisco 311 Cases  
Dataset ID: vw6y-z8j6

In [80]:
import pandas as pd
import requests

Defining the API URL

In [81]:
API_URL = "https://data.sfgov.org/resource/vw6y-z8j6.json"

Testing the connection with only 10 rows

In [82]:
params = {
    "$limit": 10,
    "$order": "requested_datetime DESC"
}

response = requests.get(API_URL, params=params, timeout=30)

print(response.status_code)

200

Looking at the raw API response

In [83]:
data = response.json()

data[:2]

[{'service_request_id': '202000046376',
  'requested_datetime': '2026-09-08T23:55:52.000',
  'updated_datetime': '2026-09-08T23:56:07.000',
  'status_description': 'Open',
  'status_notes': 'accepted',
  'agency_responsible': 'MTA - Parking Enforcement Dispatch',
  'service_name': 'Parking Enforcement',
  'service_subtype': 'parking_on_sidewalk',
  'address': '831 FULTON ST, SAN FRANCISCO, CA 94117, US',
  'street': 'FULTON ST',
  'supervisor_district': '5.0',
  'neighborhoods_sffind_boundaries': 'Hayes Valley',
  'analysis_neighborhood': 'Hayes Valley',
  'police_district': 'NORTHERN',
  'lat': '37.77780799',
  'long': '-122.43039645',
  'point': {'latitude': '37.77780799',
   'longitude': '-122.43039645',
   'human_address': '{"address": "", "city": "", "state": "", "zip": ""}'},
  'point_geom': {'type': 'Point', 'coordinates': [-122.43039645, 37.77780799]},
  'source': 'Phone',
  'data_as_of': '2026-09-09T01:00:00.000',
  'data_loaded_at': '2026-09-09T03:18:51.000'},
 {'service_request_id': '202000046374',
  'requested_datetime': '2026-09-08T23:48:58.000',
  'updated_datetime': '2026-09-08T23:49:37.000',
  'status_description': 'Open',
  'status_notes': 'open',
  'agency_responsible': 'Healthy Streets Operation Center',
  'service_name': 'Encampment',
  'service_subtype': 'encampment',
  'address': '3512 20TH ST, Yes, SAN FRANCISCO, CA 94110, US',
  'street': '20TH ST',
  'supervisor_district': '9.0',
  'neighborhoods_sffind_boundaries': 'Mission',
  'analysis_neighborhood': 'Mission',
  'police_district': 'MISSION',
  'lat': '37.75869397',
  'long': '-122.41940374',
  'point': {'latitude': '37.75869397',
   'longitude': '-122.41940374',
   'human_address': '{"address": "", "city": "", "state": "", "zip": ""}'},
  'point_geom': {'type': 'Point', 'coordinates': [-122.41940374, 37.75869397]},
  'source': 'Web',
  'media_url': {'url': 'https://sanfrancisco.form.us.empro.verintcloudservices.com/form/auto/download_attachments?caseid=202000046374&formref=VWL9Y9A7T'},
  'data_as_of': '2026-09-09T01:00:00.000',
  'data_loaded_at': '2026-09-09T03:18:51.000'}]

Converting it to a DataFrame

In [84]:
df_test = pd.DataFrame(data)

df_test.head()

,service_request_id,requested_datetime,updated_datetime,status_description,status_notes,agency_responsible,service_name,service_subtype,address,street,...,lat,long,point,point_geom,source,data_as_of,data_loaded_at,media_url,service_details,closed_date
0,202000046376,2026-09-08T23:55:52.000,2026-09-08T23:56:07.000,Open,accepted,MTA - Parking Enforcement Dispatch,Parking Enforcement,parking_on_sidewalk,"831 FULTON ST, SAN FRANCISCO, CA 94117, US",FULTON ST,...,37.77780799,-122.43039645,"{'latitude': '37.77780799', 'longitude': '-122...","{'type': 'Point', 'coordinates': [-122.4303964...",Phone,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,NaN,NaN,NaN
1,202000046374,2026-09-08T23:48:58.000,2026-09-08T23:49:37.000,Open,open,Healthy Streets Operation Center,Encampment,encampment,"3512 20TH ST, Yes, SAN FRANCISCO, CA 94110, US",20TH ST,...,37.75869397,-122.41940374,"{'latitude': '37.75869397', 'longitude': '-122...","{'type': 'Point', 'coordinates': [-122.4194037...",Web,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,{'url': 'https://sanfrancisco.form.us.empro.ve...,NaN,NaN
2,202000046372,2026-09-08T23:40:35.000,2026-09-08T23:45:35.000,Open,open,PW - Street and Environmental Services,General Request,public_works,"4322 18TH ST, SAN FRANCISCO, CA 94114, US",18TH ST,...,37.76086234,-122.43761665,"{'latitude': '37.76086234', 'longitude': '-122...","{'type': 'Point', 'coordinates': [-122.4376166...",Web,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,{'url': 'https://sanfrancisco.form.us.empro.ve...,bses request_for_service,NaN
3,202000046368,2026-09-08T23:38:03.000,2026-09-08T23:38:41.000,Open,open,PGE - Streetlights,Streetlights,light,"2120 KEITH ST, SAN FRANCISCO, CA 94124, US",KEITH ST,...,37.72787547,-122.39090588,"{'latitude': '37.72787547', 'longitude': '-122...","{'type': 'Point', 'coordinates': [-122.3909058...",Web,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,{'url': 'https://sanfrancisco.form.us.empro.ve...,light_burnt_out PGE - Streetlights,NaN
4,202000046362,2026-09-08T23:33:50.000,2026-09-08T23:33:53.000,Open,open,PUC - Billing,General Request,public_utilities_commission,"720 DELANO AVE, SAN FRANCISCO, CA 94112, US",DELANO AVE,...,37.71977239,-122.44545867,"{'latitude': '37.71977239', 'longitude': '-122...","{'type': 'Point', 'coordinates': [-122.4454586...",Phone,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,NaN,billing request_for_service,NaN

checking shape and column names

In [85]:
df_test.shape

(10, 24)

In [86]:
df_test.columns.tolist()

['service_request_id',
 'requested_datetime',
 'updated_datetime',
 'status_description',
 'status_notes',
 'agency_responsible',
 'service_name',
 'service_subtype',
 'address',
 'street',
 'supervisor_district',
 'neighborhoods_sffind_boundaries',
 'analysis_neighborhood',
 'police_district',
 'lat',
 'long',
 'point',
 'point_geom',
 'source',
 'data_as_of',
 'data_loaded_at',
 'media_url',
 'service_details',
 'closed_date']

In [87]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   service_request_id               10 non-null     object
 1   requested_datetime               10 non-null     object
 2   updated_datetime                 10 non-null     object
 3   status_description               10 non-null     object
 4   status_notes                     10 non-null     object
 5   agency_responsible               10 non-null     object
 6   service_name                     10 non-null     object
 7   service_subtype                  10 non-null     object
 8   address                          10 non-null     object
 9   street                           10 non-null     object
 10  supervisor_district              10 non-null     object
 11  neighborhoods_sffind_boundaries  10 non-null     object
 12  analysis_neighborhood            10 non-null     object
 13  police_district                  10 non-null     object
 14  lat                              10 non-null     object
 15  long                             10 non-null     object
 16  point                            10 non-null     object
 17  point_geom                       10 non-null     object
 18  source                           10 non-null     object
 19  data_as_of                       10 non-null     object
 20  data_loaded_at                   10 non-null     object
 21  media_url                        5 non-null      object
 22  service_details                  5 non-null      object
 23  closed_date                      1 non-null      object
dtypes: object(24)
memory usage: 2.0+ KB

pulling most recent 10000 rows

In [88]:
params = {
    "$limit": 10000,
    "$order": "requested_datetime DESC"
}

response = requests.get(API_URL, params=params, timeout=60)
response.raise_for_status()

records = response.json()

df = pd.DataFrame(records)

print(df.shape)

(10000, 24)

In [89]:
df.head()

,service_request_id,requested_datetime,updated_datetime,status_description,status_notes,agency_responsible,service_name,service_subtype,address,street,...,lat,long,point,point_geom,source,data_as_of,data_loaded_at,media_url,service_details,closed_date
0,202000046376,2026-09-08T23:55:52.000,2026-09-08T23:56:07.000,Open,accepted,MTA - Parking Enforcement Dispatch,Parking Enforcement,parking_on_sidewalk,"831 FULTON ST, SAN FRANCISCO, CA 94117, US",FULTON ST,...,37.77780799,-122.43039645,"{'latitude': '37.77780799', 'longitude': '-122...","{'type': 'Point', 'coordinates': [-122.4303964...",Phone,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,NaN,NaN,NaN
1,202000046374,2026-09-08T23:48:58.000,2026-09-08T23:49:37.000,Open,open,Healthy Streets Operation Center,Encampment,encampment,"3512 20TH ST, Yes, SAN FRANCISCO, CA 94110, US",20TH ST,...,37.75869397,-122.41940374,"{'latitude': '37.75869397', 'longitude': '-122...","{'type': 'Point', 'coordinates': [-122.4194037...",Web,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,{'url': 'https://sanfrancisco.form.us.empro.ve...,NaN,NaN
2,202000046372,2026-09-08T23:40:35.000,2026-09-08T23:45:35.000,Open,open,PW - Street and Environmental Services,General Request,public_works,"4322 18TH ST, SAN FRANCISCO, CA 94114, US",18TH ST,...,37.76086234,-122.43761665,"{'latitude': '37.76086234', 'longitude': '-122...","{'type': 'Point', 'coordinates': [-122.4376166...",Web,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,{'url': 'https://sanfrancisco.form.us.empro.ve...,bses request_for_service,NaN
3,202000046368,2026-09-08T23:38:03.000,2026-09-08T23:38:41.000,Open,open,PGE - Streetlights,Streetlights,light,"2120 KEITH ST, SAN FRANCISCO, CA 94124, US",KEITH ST,...,37.72787547,-122.39090588,"{'latitude': '37.72787547', 'longitude': '-122...","{'type': 'Point', 'coordinates': [-122.3909058...",Web,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,{'url': 'https://sanfrancisco.form.us.empro.ve...,light_burnt_out PGE - Streetlights,NaN
4,202000046362,2026-09-08T23:33:50.000,2026-09-08T23:33:53.000,Open,open,PUC - Billing,General Request,public_utilities_commission,"720 DELANO AVE, SAN FRANCISCO, CA 94112, US",DELANO AVE,...,37.71977239,-122.44545867,"{'latitude': '37.71977239', 'longitude': '-122...","{'type': 'Point', 'coordinates': [-122.4454586...",Phone,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,NaN,billing request_for_service,NaN

In [90]:
df.tail()

,service_request_id,requested_datetime,updated_datetime,status_description,status_notes,agency_responsible,service_name,service_subtype,address,street,...,lat,long,point,point_geom,source,data_as_of,data_loaded_at,media_url,service_details,closed_date
9995,202000032712,2026-09-04T12:38:39.000,2026-09-04T12:53:32.000,Closed,NaN,Recology - Abandoned,Street and Sidewalk Cleaning,garbage_and_debris,"1504 BRYANT ST, SAN FRANCISCO, CA 94103, US",BRYANT ST,...,37.76788197268714,-122.41077485640453,"{'latitude': '37.76788197268714', 'longitude':...","{'type': 'Point', 'coordinates': [-122.4107748...",Mobile,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,{'url': 'https://spot-sf-res.cloudinary.com/im...,other_bagged_boxed_contained_garbage,2026-09-04T12:53:26.000
9996,202000032708,2026-09-04T12:37:33.000,2026-09-07T12:37:34.000,Closed,case_resolved - No Work Needed,PW - Street and Environmental Services,Street and Sidewalk Cleaning,garbage_and_debris,"143 LEXINGTON ST, SAN FRANCISCO, CA 94110, US",LEXINGTON ST,...,37.76105920867902,-122.4206136987341,"{'latitude': '37.76105920867902', 'longitude':...","{'type': 'Point', 'coordinates': [-122.4206136...",Mobile,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,{'url': 'https://spot-sf-res.cloudinary.com/im...,other_loose_garbage_debris_yard_waste,2026-09-07T13:31:48.000
9997,202000032707,2026-09-04T12:37:07.000,2026-09-06T08:17:25.000,Closed,case_resolved - Resolved,PW - Street and Environmental Services,Street and Sidewalk Cleaning,garbage_and_debris,"811 14TH ST, SAN FRANCISCO, CA 94114, US",14TH ST,...,37.76756572994036,-122.4315812514244,"{'latitude': '37.76756572994036', 'longitude':...","{'type': 'Point', 'coordinates': [-122.4315812...",Mobile,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,{'url': 'https://spot-sf-res.cloudinary.com/im...,human_waste_or_urine,2026-09-06T09:12:38.000
9998,202000032706,2026-09-04T12:36:56.000,2026-09-05T09:23:10.000,Closed,case_resolved - No Work Needed,PW - Street and Environmental Services,Street and Sidewalk Cleaning,garbage_and_debris,"2944 ULLOA ST, SAN FRANCISCO, CA 94116, US",ULLOA ST,...,37.74080333333333,-122.48815333333333,"{'latitude': '37.74080333333333', 'longitude':...","{'type': 'Point', 'coordinates': [-122.4881533...",Mobile,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,{'url': 'https://spot-sf-res.cloudinary.com/im...,other_loose_garbage_debris_yard_waste,2026-09-05T10:20:08.000
9999,202000032705,2026-09-04T12:36:54.000,2026-09-04T15:54:38.000,Closed,case_resolved - Officer responded to request u...,MTA - Parking Enforcement Dispatch,Parking Enforcement,parking_on_sidewalk,"148 BRODERICK ST, Yes, SAN FRANCISCO, CA 94117...",BRODERICK ST,...,37.77152907,-122.43870082,"{'latitude': '37.77152907', 'longitude': '-122...","{'type': 'Point', 'coordinates': [-122.4387008...",Web,2026-09-09T01:00:00.000,2026-09-09T03:18:51.000,{'url': 'https://sanfrancisco.form.us.empro.ve...,NaN,2026-09-04T16:54:35.000

print all column names

In [91]:
for column in df.columns:
    print(column)

service_request_id
requested_datetime
updated_datetime
status_description
status_notes
agency_responsible
service_name
service_subtype
address
street
supervisor_district
neighborhoods_sffind_boundaries
analysis_neighborhood
police_district
lat
long
point
point_geom
source
data_as_of
data_loaded_at
media_url
service_details
closed_date

In [92]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

Rows: 10000
Columns: 24

checking missing values

In [93]:
missing = df.isna().sum().sort_values(ascending=False)

missing

closed_date                        3579
service_details                    3279
media_url                          2987
status_notes                       1797
street                              115
analysis_neighborhood               103
point                               101
lat                                 101
point_geom                          101
long                                101
police_district                      84
supervisor_district                  71
neighborhoods_sffind_boundaries      69
requested_datetime                    0
service_request_id                    0
updated_datetime                      0
service_subtype                       0
service_name                          0
agency_responsible                    0
status_description                    0
address                               0
source                                0
data_as_of                            0
data_loaded_at                        0
dtype: int64

In [94]:
missing_pct = (
    df.isna().mean()
    .mul(100)
    .round(2)
    .sort_values(ascending=False)
)

missing_pct

closed_date                        35.79
service_details                    32.79
media_url                          29.87
status_notes                       17.97
street                              1.15
analysis_neighborhood               1.03
point                               1.01
lat                                 1.01
point_geom                          1.01
long                                1.01
police_district                     0.84
supervisor_district                 0.71
neighborhoods_sffind_boundaries     0.69
requested_datetime                  0.00
service_request_id                  0.00
updated_datetime                    0.00
service_subtype                     0.00
service_name                        0.00
agency_responsible                  0.00
status_description                  0.00
address                             0.00
source                              0.00
data_as_of                          0.00
data_loaded_at                      0.00
dtype: float64

. Checking duplicate request IDs

In [95]:
df["service_request_id"].nunique()

10000

In [96]:
len(df)

10000

In [97]:
duplicate_ids = df["service_request_id"].duplicated().sum()

print("Duplicate request IDs:", duplicate_ids)

Duplicate request IDs: 0

Checking missing request IDs

In [98]:
df["service_request_id"].isna().sum()

np.int64(0)

Looking at statuses

In [99]:
df["status_description"].value_counts(dropna=False)

status_description
Closed    6421
Open      3579
Name: count, dtype: int64

In [100]:
df["status_description"].value_counts(
    normalize=True,
    dropna=False
).mul(100).round(2)

status_description
Closed    64.21
Open      35.79
Name: proportion, dtype: float64

Looking at service categories

In [101]:
df["service_name"].value_counts().head(20)

service_name
Street and Sidewalk Cleaning                 4015
Parking Enforcement                          2163
General Request                               715
Graffiti Public                               619
Encampment                                    426
Blocked Street and Sidewalk                   305
Noise                                         273
Graffiti Private                              227
RPD General                                   197
Tree Maintenance                              140
Litter Receptacle Maintenance                 134
Damage Property                               103
Street Defect                                 100
Muni Service Feedback                          94
Sewer                                          84
Sidewalk and Curb                              80
Muni Employee Feedback                         70
Streetlights                                   64
MTA Parking Traffic Signs Normal Priority      60
Residential Building                           56
Name: count, dtype: int64

In [102]:
print("Number of service categories:", df["service_name"].nunique())

Number of service categories: 31

Looking at subtypes, agencies, neighborhoods, and source

In [103]:
df["service_subtype"].value_counts().head(20)

service_subtype
garbage_and_debris                     4014
not_offensive                           800
other_illegal_parking                   718
blocking_driveway_cite_only             454
parking_on_sidewalk                     435
encampment                              426
homelessness_and_supportive_housing     363
blocked_sidewalk                        294
blocking_driveway_cite_tow              254
abandoned_vehicle                       246
other_excessive_noise                   157
municipal_transportation_agency         135
public_works                            133
sidewalk_defect                          79
park_services_area                       73
other                                    72
park_patrol                              67
damaged_tree                             54
structural_maintenance                   51
light                                    49
Name: count, dtype: int64

In [104]:
df["service_subtype"].nunique()

150

In [105]:
df["agency_responsible"].value_counts().head(20)

agency_responsible
PW - Street and Environmental Services     2769
MTA - Parking Enforcement Dispatch         1768
Recology - Abandoned                       1515
Healthy Streets Operation Center            727
MTA - Access/Mobility Services Received     309
Recology - Overflowing                      305
MTA - Abandoned Vehicles Work               303
Noise Report                                212
PW - Street Use and Mapping                 207
MTA - Muni Feedback Received                185
PW - Urban Forestry                         109
Clear Channel - Transit                      99
Recology - Litter                            94
CBD - Tenderloin                             80
311 - Supervisor                             78
MTA - Parking Enforcement                    68
PUC - Sewer Ops                              61
MTA - Sign Shop                              60
RPD - PSA                                    56
US Postal Service Maintenance                56
Name: count, dtype: int64

In [106]:
df["analysis_neighborhood"].value_counts().head(20)

analysis_neighborhood
Mission                           1532
South of Market                    586
Tenderloin                         492
Hayes Valley                       422
Haight Ashbury                     408
Sunset/Parkside                    404
Bayview Hunters Point              376
Castro/Upper Market                353
Outer Richmond                     348
Financial District/South Beach     342
Nob Hill                           338
Bernal Heights                     317
Marina                             302
Excelsior                          275
Inner Richmond                     264
Western Addition                   229
Outer Mission                      217
West of Twin Peaks                 215
North Beach                        212
Inner Sunset                       207
Name: count, dtype: int64

In [107]:
print(
    "Neighborhoods:",
    df["analysis_neighborhood"].nunique()
)

Neighborhoods: 41

In [108]:
df["source"].value_counts(dropna=False)

source
Mobile               4387
Web                  3758
Phone                1761
Integrated Agency      74
Test                   15
Twitter                 5
Name: count, dtype: int64

Convert the date columns

In [109]:
date_columns = [
    "requested_datetime",
    "updated_datetime",
    "closed_date"
]

for column in date_columns:
    df[column] = pd.to_datetime(
        df[column],
        errors="coerce"
    )

In [110]:
df[date_columns].dtypes

requested_datetime    datetime64[ns]
updated_datetime      datetime64[ns]
closed_date           datetime64[ns]
dtype: object

checking sample date range

In [111]:
print(
    "Earliest request:",
    df["requested_datetime"].min()
)

print(
    "Latest request:",
    df["requested_datetime"].max()
)

Earliest request: 2026-09-04 12:36:54
Latest request: 2026-09-08 23:55:52

Checking the date range of the exploration sample

In [112]:
dataset_summary = {
    "first_request": df["requested_datetime"].min(),
    "latest_request": df["requested_datetime"].max(),
    "total_rows_in_sample": len(df)
}

dataset_summary

{'first_request': Timestamp('2026-09-04 12:36:54'),
 'latest_request': Timestamp('2026-09-08 23:55:52'),
 'total_rows_in_sample': 10000}

In [113]:
pd.DataFrame([dataset_summary])

        first_request      latest_request  total_rows_in_sample
0 2026-09-04 12:36:54 2026-09-08 23:55:52                 10000

Check missing timestamps after conversion

In [114]:
df[date_columns].isna().sum()

requested_datetime       0
updated_datetime         0
closed_date           3579
dtype: int64

Checking impossible close dates

In [115]:
invalid_close_dates = df[
    df["closed_date"].notna()
    & (
        df["closed_date"]
        < df["requested_datetime"]
    )
]

print(
    "Closed before opened:",
    len(invalid_close_dates)
)

Closed before opened: 11

In [116]:
invalid_close_dates[
    [
        "service_request_id",
        "requested_datetime",
        "closed_date",
        "status_description",
        "service_name"
    ]
].head(20)

,service_request_id,requested_datetime,closed_date,status_description,service_name
1165,202000044791,2026-09-08 13:55:53,2026-09-08 01:00:00,Closed,Graffiti Private
1294,202000044604,2026-09-08 13:06:51,2026-09-08 01:00:00,Closed,Graffiti Private
1336,202000044547,2026-09-08 12:53:51,2026-09-08 01:00:00,Closed,Graffiti Private
1800,202000043908,2026-09-08 10:36:27,2026-09-08 01:00:00,Closed,Graffiti Private
1825,202000043875,2026-09-08 10:30:57,2026-09-08 01:00:00,Closed,Graffiti Private
2007,202000043627,2026-09-08 09:39:18,2026-09-08 01:00:00,Closed,Graffiti Private
2067,202000043553,2026-09-08 09:24:52,2026-09-08 01:00:00,Closed,Blocked Street and Sidewalk
2145,202000043451,2026-09-08 09:05:57,2026-09-08 01:00:00,Closed,Blocked Street and Sidewalk
2284,202000043288,2026-09-08 08:38:52,2026-09-08 01:00:00,Closed,Graffiti Private
2440,202000043089,2026-09-08 08:05:06,2026-09-08 01:00:00,Closed,General Request
9991,202000032716,2026-09-04 12:39:53,2026-09-04 01:00:00,Closed,Graffiti Private

Calculate sample resolution time

In [117]:
closed_cases = df[
    df["closed_date"].notna()
].copy()

In [118]:
closed_cases["resolution_hours"] = (
    closed_cases["closed_date"]
    - closed_cases["requested_datetime"]
).dt.total_seconds() / 3600

In [119]:
closed_cases["resolution_hours"].describe()

count    6421.000000
mean       12.971576
std        19.975048
min       -12.931389
25%         1.424722
50%         3.194722
75%        16.321667
max       102.757222
Name: resolution_hours, dtype: float64

In [120]:
closed_cases["resolution_hours"].median()

3.194722222222222

In [121]:
closed_cases["resolution_hours"].quantile(0.90)

np.float64(42.264722222222225)

Checking negative resolution times

In [122]:
(closed_cases["resolution_hours"] < 0).sum()

np.int64(11)

In [123]:
closed_cases[
    [
        "service_request_id",
        "service_name",
        "requested_datetime",
        "closed_date",
        "resolution_hours"
    ]
].sort_values(
    "resolution_hours",
    ascending=False
).head(20)

,service_request_id,service_name,requested_datetime,closed_date,resolution_hours
9759,202000033065,Street and Sidewalk Cleaning,2026-09-04 14:12:09,2026-09-08 20:57:35,102.757222
9767,202000033052,Street and Sidewalk Cleaning,2026-09-04 14:08:55,2026-09-08 20:16:05,102.119444
9746,202000033086,Street and Sidewalk Cleaning,2026-09-04 14:15:05,2026-09-08 20:02:07,101.783889
9419,202000033553,Street and Sidewalk Cleaning,2026-09-04 16:35:52,2026-09-08 21:54:33,101.311389
9388,202000033590,Street and Sidewalk Cleaning,2026-09-04 16:47:52,2026-09-08 21:03:56,100.267778
9506,202000033433,Street and Sidewalk Cleaning,2026-09-04 15:58:13,2026-09-08 19:41:29,99.721111
9706,202000033141,Damage Property,2026-09-04 14:31:00,2026-09-08 18:00:42,99.495000
9220,202000033812,Street and Sidewalk Cleaning,2026-09-04 17:45:19,2026-09-08 21:07:23,99.367778
9216,202000033817,Street and Sidewalk Cleaning,2026-09-04 17:46:40,2026-09-08 21:01:49,99.252500
8977,202000034132,Street and Sidewalk Cleaning,2026-09-04 19:34:53,2026-09-08 21:47:05,98.203333
8928,202000034210,General Request,2026-09-04 20:21:12,2026-09-08 21:40:14,97.317222
9551,202000033371,Street and Sidewalk Cleaning,2026-09-04 15:45:07,2026-09-08 16:48:22,97.054167
9792,202000033024,General Request,2026-09-04 14:03:20,2026-09-08 15:03:32,97.003333
9620,202000033276,Street Defect,2026-09-04 15:12:03,2026-09-08 15:28:36,96.275833
9574,202000033332,General Request,2026-09-04 15:33:51,2026-09-08 15:49:33,96.261667
9529,202000033400,Muni Service Feedback,2026-09-04 15:50:05,2026-09-08 15:56:11,96.101667
9743,202000033089,Graffiti Private,2026-09-04 14:16:52,2026-09-08 13:57:05,95.670278
9985,202000032725,Street Defect,2026-09-04 12:41:57,2026-09-08 11:40:19,94.972778
9420,202000033552,General Request,2026-09-04 16:35:36,2026-09-08 15:31:31,94.931944
9427,202000033539,Street Defect,2026-09-04 16:32:13,2026-09-08 15:15:39,94.723889

Check open cases versus status

In [124]:
open_cases = df[
    df["closed_date"].isna()
].copy()

print("Open cases in sample:", len(open_cases))

Open cases in sample: 3579

In [125]:
pd.crosstab(
    df["status_description"],
    df["closed_date"].isna(),
    margins=True
)

closed_date         False  True    All
status_description
Closed               6421     0   6421
Open                    0  3579   3579
All                  6421  3579  10000

Validate incoming-requests KPI

In [126]:
daily_incoming = (
    df.groupby(
        df["requested_datetime"].dt.date
    )["service_request_id"]
    .nunique()
    .reset_index(name="incoming_requests")
)

daily_incoming.head()

  requested_datetime  incoming_requests
0         2026-09-04               1226
1         2026-09-05               1896
2         2026-09-06               1898
3         2026-09-07               2128
4         2026-09-08               2852

In [127]:
daily_incoming.tail()

  requested_datetime  incoming_requests
0         2026-09-04               1226
1         2026-09-05               1896
2         2026-09-06               1898
3         2026-09-07               2128
4         2026-09-08               2852

Checking requests by category

In [128]:
requests_by_category = (
    df.groupby("service_name")
    ["service_request_id"]
    .nunique()
    .sort_values(ascending=False)
)

requests_by_category.head(15)

service_name
Street and Sidewalk Cleaning     4015
Parking Enforcement              2163
General Request                   715
Graffiti Public                   619
Encampment                        426
Blocked Street and Sidewalk       305
Noise                             273
Graffiti Private                  227
RPD General                       197
Tree Maintenance                  140
Litter Receptacle Maintenance     134
Damage Property                   103
Street Defect                     100
Muni Service Feedback              94
Sewer                              84
Name: service_request_id, dtype: int64

Cross-check category and status

In [129]:
category_status = pd.crosstab(
    df["service_name"],
    df["status_description"]
)

category_status.head(20)

status_description                         Closed  Open
service_name
Autonomous Vehicle Complaints                   0    13
Blocked Street and Sidewalk                   260    45
Citations Questions Comments                    1     0
Damage Property                                36    67
Encampment                                    238   188
General Request                               430   285
Graffiti Private                               62   165
Graffiti Public                               105   514
Illegal Postings                                1     9
Litter Receptacle Maintenance                  61    73
MTA Parking Traffic Signs High Priority         6     9
MTA Parking Traffic Signs Normal Priority       5    55
Muni Employee Feedback                         18    52
Muni Service Feedback                          41    53
Noise                                         179    94
Parking Enforcement                          1858   305
RPD General                                    83   114
RPP Application Status                          1     0
Residential Building                           35    21
Sewer                                          59    25

Checking required columns

In [130]:
required_columns = [
    "service_request_id",
    "requested_datetime",
    "closed_date",
    "updated_datetime",
    "status_description",
    "agency_responsible",
    "service_name",
    "service_subtype",
    "analysis_neighborhood",
    "source"
]

missing_columns = [
    column
    for column in required_columns
    if column not in df.columns
]

print("Missing required columns:", missing_columns)

Missing required columns: []

Createing a small profile table

In [131]:
profile = []

for column in required_columns:
    profile.append({
        "column": column,
        "dtype": str(df[column].dtype),
        "missing": df[column].isna().sum(),
        "missing_pct": round(
            df[column].isna().mean() * 100,
            2
        ),
        "unique_values": df[column].nunique(
            dropna=True
        )
    })

profile_df = pd.DataFrame(profile)

profile_df

                  column           dtype  missing  missing_pct  unique_values
0     service_request_id          object        0         0.00          10000
1     requested_datetime  datetime64[ns]        0         0.00           9320
2            closed_date  datetime64[ns]     3579        35.79           6078
3       updated_datetime  datetime64[ns]        0         0.00           9263
4     status_description          object        0         0.00              2
5     agency_responsible          object        0         0.00            100
6           service_name          object        0         0.00             31
7        service_subtype          object        0         0.00            150
8  analysis_neighborhood          object      103         1.03             41
9                 source          object        0         0.00              6

INITIAL FINDINGS

## Initial Findings

I pulled the 10,000 most recent SF311 cases to get a better understanding of the data before building the warehouse.

What I found:

- I did not find any duplicate or missing `service_request_id` values in this sample.
- The data has a good amount of detail, including multiple service categories, subtypes, and neighborhoods.
- A good number of records do not have a `closed_date`, which makes sense because those requests are still open.
- I found 11 records where the `closed_date` is earlier than the `requested_datetime`, so those records will need to be checked before using them in resolution-time calculations.

Things I need to handle later:

- Some fields, especially the date fields, come in as strings and will need to be converted properly in the staging layer.
- Resolution-time calculations will need some data-quality checks so invalid or unusual records do not affect the final metrics.

## Decisions From This Exploration

For the first warehouse version:

- I will use `service_request_id` as the main request key and check uniqueness again when I load the full historical data.
- Date fields will be converted explicitly instead of relying on automatic type detection.
- I will use `analysis_neighborhood` as the main neighborhood field for reporting.
- Historical backlog will be calculated using the request and close dates instead of relying only on the current status.
- I will keep the raw source data unchanged before applying any cleaning or transformations.
- Records with questionable dates will be flagged and reviewed instead of being silently changed.
- Negative resolution times will not be included in valid resolution-time metrics until those records are investigated.

These decisions may change later if the full historical data shows issues that are not visible in this sample.